[package]

name = "protobuf"
version = "2.8.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stepancheg/rust-protobuf/"
repository = "https://github.com/stepancheg/rust-protobuf/"
documentation = "https://github.com/stepancheg/rust-protobuf/blob/master/README.md"
description = """
Rust implementation of Google protocol buffers
"""

[lib]
doctest = false
bench = false

[features]
with-bytes = ["bytes"]
with-serde = ["serde", "serde_derive"]

[dependencies]
bytes = { version = "1", optional = true }
serde        = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
hex = "0.3"
heck = "0.3"

[package.metadata.docs.rs]
all-features = true
