[package]
name = "protobuf-codegen-pure"
version = "2.8.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure/"
repository = "https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure/"
description = """
Pure-rust codegen for protobuf using protobuf-parser crate

WIP
"""

[lib]
doctest = false

[dependencies]
protobuf = { path = "../protobuf", version = "2.8.0" }
protobuf-codegen = { path = "../protobuf-codegen", version = "2.8.0" }
protobuf-parser = "=0.1.2"
